---

name: Check syntax with linters

'on':
  push:
    branches:
      - main
  pull_request:

jobs:
  check-yaml-syntax:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Run yamllint with python3
        uses: actions/setup-python@v4.2.0
        with:
          python-version: '3.x'
      - run: python3 -m pip install yamllint
      - run: yamllint --config-file .yamllint.yml .
  check-ansible-syntax:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Run ansible-lint-action
        uses: ansible/ansible-lint-action@v6.5.2

...